import type { Metadata } from "next";
import { Red_Hat_Display, Red_Hat_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-Hat-Display",
  display: "swap",
});

const redHatMono = Red_Hat_Mono({
  subsets: ["latin"],
  variable: "--font-red-Hat-Mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(redHatDisplay.variable, redHatMono.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
