// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  article_preview: dynamic(() => import("./ArticlePreview")),
  gallery: dynamic(() => import("./Gallery")),
};
